//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess_club_manager.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все игроки.
        /// </summary>
        public static string AllPlayers {
            get {
                return ResourceManager.GetString("AllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweed Sugar Chess.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Арбитры.
        /// </summary>
        public static string Arbitrators {
            get {
                return ResourceManager.GetString("Arbitrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад к профилю.
        /// </summary>
        public static string BackToProfile {
            get {
                return ResourceManager.GetString("BackToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите Язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата Создания.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее изображение.
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить изображение.
        /// </summary>
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь \ язык.
        /// </summary>
        public static string HelpLanguage {
            get {
                return ResourceManager.GetString("HelpLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домой.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess Club Manager это современное Веб приложение для автоматизации процессов шахматного клуба.
        /// </summary>
        public static string HomeJumbotronInfo {
            get {
                return ResourceManager.GetString("HomeJumbotronInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная Страница.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string LogInfo {
            get {
                return ResourceManager.GetString("LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логи.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип лога.
        /// </summary>
        public static string LogType {
            get {
                return ResourceManager.GetString("LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string LogWarning {
            get {
                return ResourceManager.GetString("LogWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки Email .
        /// </summary>
        public static string MailSettings {
            get {
                return ResourceManager.GetString("MailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string ManageDropdown {
            get {
                return ResourceManager.GetString("ManageDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка нового изображения.
        /// </summary>
        public static string NewImage {
            get {
                return ResourceManager.GetString("NewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Официальный.
        /// </summary>
        public static string Official {
            get {
                return ResourceManager.GetString("Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диаграмма рейтинга.
        /// </summary>
        public static string PlayerChart {
            get {
                return ResourceManager.GetString("PlayerChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string PlayerInfo {
            get {
                return ResourceManager.GetString("PlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string PlayerRating {
            get {
                return ResourceManager.GetString("PlayerRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игроки.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Титул.
        /// </summary>
        public static string PlayerTitle {
            get {
                return ResourceManager.GetString("PlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытый.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытый.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущие Турниры.
        /// </summary>
        public static string TopCurrentTrns {
            get {
                return ResourceManager.GetString("TopCurrentTrns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Близжайшие Турниры.
        /// </summary>
        public static string TopFutureTrns {
            get {
                return ResourceManager.GetString("TopFutureTrns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прошедшие Турниры.
        /// </summary>
        public static string TopLastTrns {
            get {
                return ResourceManager.GetString("TopLastTrns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг игроков.
        /// </summary>
        public static string TopPlayersRating {
            get {
                return ResourceManager.GetString("TopPlayersRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать результаты.
        /// </summary>
        public static string TourEditResults {
            get {
                return ResourceManager.GetString("TourEditResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турнир.
        /// </summary>
        public static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турниры.
        /// </summary>
        public static string Tournaments {
            get {
                return ResourceManager.GetString("Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники.
        /// </summary>
        public static string TRNassignedPlayersCount {
            get {
                return ResourceManager.GetString("TRNassignedPlayersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать Турнир.
        /// </summary>
        public static string TRNcreate {
            get {
                return ResourceManager.GetString("TRNcreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создатель Турнира.
        /// </summary>
        public static string TRNcreator {
            get {
                return ResourceManager.GetString("TRNcreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение.
        /// </summary>
        public static string TRNfinish {
            get {
                return ResourceManager.GetString("TRNfinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат Турнира.
        /// </summary>
        public static string TRNformat {
            get {
                return ResourceManager.GetString("TRNformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат игры.
        /// </summary>
        public static string TRNgameResult {
            get {
                return ResourceManager.GetString("TRNgameResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная Информация.
        /// </summary>
        public static string TRNinfo {
            get {
                return ResourceManager.GetString("TRNinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен.
        /// </summary>
        public static string TRNisCompleted {
            get {
                return ResourceManager.GetString("TRNisCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турнир завершен.
        /// </summary>
        public static string TRNisCompletedYet {
            get {
                return ResourceManager.GetString("TRNisCompletedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турнир в процессе.
        /// </summary>
        public static string TRNisInProcess {
            get {
                return ResourceManager.GetString("TRNisInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string TRNisOfficial {
            get {
                return ResourceManager.GetString("TRNisOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ.
        /// </summary>
        public static string TRNisPrivate {
            get {
                return ResourceManager.GetString("TRNisPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начался.
        /// </summary>
        public static string TRNisStarted {
            get {
                return ResourceManager.GetString("TRNisStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место проведения.
        /// </summary>
        public static string TRNlocation {
            get {
                return ResourceManager.GetString("TRNlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление Арбитрами.
        /// </summary>
        public static string TRNmanageArbitrators {
            get {
                return ResourceManager.GetString("TRNmanageArbitrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление Игроками.
        /// </summary>
        public static string TRNmanagePlayers {
            get {
                return ResourceManager.GetString("TRNmanagePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. игроков.
        /// </summary>
        public static string TRNmaxPlayersCount {
            get {
                return ResourceManager.GetString("TRNmaxPlayersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное количество туров.
        /// </summary>
        public static string TRNMaxToursCount {
            get {
                return ResourceManager.GetString("TRNMaxToursCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название Турнира.
        /// </summary>
        public static string TRNname {
            get {
                return ResourceManager.GetString("TRNname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string TRNstart {
            get {
                return ResourceManager.GetString("TRNstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контроль времени (мин.).
        /// </summary>
        public static string TRNtimeControl {
            get {
                return ResourceManager.GetString("TRNtimeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тур.
        /// </summary>
        public static string TRNtour {
            get {
                return ResourceManager.GetString("TRNtour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершен.
        /// </summary>
        public static string TRNtourComplatedDate {
            get {
                return ResourceManager.GetString("TRNtourComplatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тур завершен.
        /// </summary>
        public static string TRNtourCompleted {
            get {
                return ResourceManager.GetString("TRNtourCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тур в процессе.
        /// </summary>
        public static string TRNtourInProcess {
            get {
                return ResourceManager.GetString("TRNtourInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туры.
        /// </summary>
        public static string TRNtours {
            get {
                return ResourceManager.GetString("TRNtours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string TRNtourStatus {
            get {
                return ResourceManager.GetString("TRNtourStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат Турнира.
        /// </summary>
        public static string TRNtype {
            get {
                return ResourceManager.GetString("TRNtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неофициальный.
        /// </summary>
        public static string UnOfficial {
            get {
                return ResourceManager.GetString("UnOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали пользователя.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
