//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess_club_manager.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSettings
    {
        public int Id { get; set; }
        public string MailFrom { get; set; }
        public string MailPassword { get; set; }
        public string MailServer { get; set; }
        public int MailPort { get; set; }
        public bool EnableSsl { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
