//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess_club_manager.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournaments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournaments()
        {
            this.TournamentTours = new HashSet<TournamentTours>();
            this.AspNetUsers1 = new HashSet<AspNetUsers>();
            this.AspNetUsers2 = new HashSet<AspNetUsers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> Finish { get; set; }
        public string Info { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsOfficial { get; set; }
        public int TimeControl { get; set; }
        public string Location { get; set; }
        public bool IsPrivate { get; set; }
        public int MaxPlayersCount { get; set; }
        public int MaxToursCount { get; set; }
        public int Format { get; set; }
        public bool IsStarted { get; set; }
        public bool IsCompleted { get; set; }
        public string CreatorId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentTours> TournamentTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers2 { get; set; }
    }
}
