//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess_club_manager.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentTours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TournamentTours()
        {
            this.TourGames = new HashSet<TourGames>();
        }
    
        public int Id { get; set; }
        public int TournamentId { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Number { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourGames> TourGames { get; set; }
        public virtual Tournaments Tournaments { get; set; }
    }
}
